const SUPABASE_URL = "https://SEU-PROJETO.supabase.co";
const SUPABASE_ANON_KEY = "SUA_CHAVE_ANON_AQUI";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const byId = (id) => document.getElementById(id);
let candidates = [], leads = [], jobs = [], activeCandidate = null, loadedUserId = null, jobsRetryCount = 0;

function setLoading(button, loading) { button.disabled = loading; button.textContent = loading ? "Verificando acesso..." : "Acessar painel →"; }
byId("auth-form").addEventListener("submit", async (event) => { event.preventDefault(); const button=byId("login-button"),status=byId("auth-status"); status.textContent="";setLoading(button,true);const{error}=await supabaseClient.auth.signInWithPassword({email:byId("email").value.trim(),password:byId("senha").value});if(error){status.textContent="E-mail ou senha inválidos. Verifique os dados e tente novamente.";setLoading(button,false)}});
byId("logout-button").addEventListener("click", async()=>{await supabaseClient.auth.signOut()});
function showLogin(){byId("login-form").hidden=false;byId("painel-interno").hidden=true;loadedUserId=null;setLoading(byId("login-button"),false)}
function showDashboard(session){byId("login-form").hidden=true;byId("painel-interno").hidden=false;setLoading(byId("login-button"),false);byId("user-email").textContent=session.user.email||"";byId("user-avatar").textContent=(session.user.email||"AR").slice(0,2).toUpperCase();if(loadedUserId!==session.user.id){loadedUserId=session.user.id;loadWorkspace()}}

const viewCopy={talents:["Workspace / Banco de talentos","Banco de talentos","Visualize, filtre e acompanhe os profissionais cadastrados."],leads:["Workspace / Empresas","Empresas interessadas","Organize contatos comerciais recebidos pelo site."],jobs:["Workspace / Vagas","Gestão de vagas","Publique e acompanhe oportunidades do portal de carreiras."]};
document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.view)));
function switchView(view){document.querySelectorAll("[data-view]").forEach(button=>button.classList.toggle("active",button.dataset.view===view));document.querySelectorAll(".workspace-view").forEach(section=>{const active=section.id===`view-${view}`;section.hidden=!active;section.classList.toggle("active",active)});const copy=viewCopy[view];byId("breadcrumb").textContent=copy[0];byId("view-title").textContent=copy[1];byId("view-description").textContent=copy[2]}

async function loadWorkspace(){await Promise.all([loadCandidates(),loadLeads(),loadJobs()]);updateMetrics()}
async function loadCandidates(){const{data,error}=await supabaseClient.from("candidatos").select("*");if(error){console.error("Falha ao consultar candidatos:",error);renderTableError("lista-candidatos",5,"Não foi possível carregar os candidatos.");return}candidates=data||[];populateAreas();renderCandidates()}
async function loadLeads(){const{data,error}=await supabaseClient.from("leads_empresas").select("*");if(error){console.error("Falha ao consultar leads:",error);renderTableError("lista-leads",5,"Não foi possível carregar os contatos empresariais.");return}leads=data||[];renderLeads()}
async function loadJobs(){const{data,error}=await supabaseClient.from("vagas").select("*");if(error){console.error("Falha ao consultar vagas:",error);jobs=[];renderJobsAdmin(true);if(jobsRetryCount<4){jobsRetryCount+=1;setTimeout(loadJobs,1800)}return}jobsRetryCount=0;jobs=data||[];renderJobsAdmin(false);updateMetrics()}
function updateMetrics(){byId("metric-total").textContent=candidates.length;byId("metric-leads").textContent=leads.length;byId("metric-jobs").textContent=jobs.filter(job=>job.ativa!==false).length;byId("nav-talents-count").textContent=candidates.length;byId("nav-leads-count").textContent=leads.length;byId("nav-jobs-count").textContent=jobs.length;renderAnalytics()}
function renderAnalytics(){const stages=["novo","triagem","entrevista","finalista","contratado"],pipeline=byId("pipeline-steps");pipeline.replaceChildren();stages.forEach(stage=>{const item=textElement("div","pipeline-step"),count=candidates.filter(candidate=>stageOf(candidate)===stage).length;item.append(textElement("strong","",count),textElement("span","",stageLabel(stage)));pipeline.append(item)});const areas=[...new Set(candidates.map(areaOf))].map(area=>({area,count:candidates.filter(candidate=>areaOf(candidate)===area).length})).sort((a,b)=>b.count-a.count).slice(0,5),chart=byId("area-chart"),max=Math.max(1,...areas.map(item=>item.count));chart.replaceChildren();if(!areas.length){chart.append(textElement("p","chart-empty","Os dados aparecerão conforme os cadastros."));return}areas.forEach(item=>{const row=textElement("div","area-chart-row"),label=textElement("span","",item.area),track=textElement("i","area-chart-track"),bar=textElement("b","area-chart-bar"),count=textElement("strong","",item.count);bar.style.width=`${Math.max(8,item.count/max*100)}%`;track.append(bar);row.append(label,track,count);chart.append(row)})}

function normalize(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function areaOf(candidate){return candidate.vaga_interesse||"Geral"}function stageOf(candidate){return candidate.status_processo||"novo"}function phoneDigits(phone){return String(phone||"").replace(/\D/g,"")}function initials(name){return String(name||"Talento").split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function textElement(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;el.textContent=text??"—";return el}
function personBlock(candidate){const wrap=textElement("div","person"),avatar=textElement("span","person-avatar",initials(candidate.nome)),details=document.createElement("div");details.append(textElement("strong","",candidate.nome||"Nome não informado"),textElement("small","",candidate.tags||"Candidato cadastrado"));wrap.append(avatar,details);return wrap}
function actionLink(label,href,className=""){const link=textElement("a",`action-link ${className}`,label);link.href=href;link.target="_blank";link.rel="noopener noreferrer";return link}
function whatsappUrl(person){const digits=phoneDigits(person.telefone||person.telefone_empresa);const target=digits.startsWith("55")?digits:`55${digits}`;return `https://wa.me/${target}`}
function populateAreas(){const select=byId("area-filter"),current=select.value;[...select.options].slice(1).forEach(option=>option.remove());[...new Set(candidates.map(areaOf))].sort((a,b)=>a.localeCompare(b,"pt-BR")).forEach(area=>{const option=textElement("option","",area);option.value=area;select.append(option)});select.value=current}
function filteredCandidates(){const term=normalize(byId("search-input").value),area=byId("area-filter").value,stage=byId("stage-filter").value;return candidates.filter(candidate=>(!term||normalize(`${candidate.nome} ${candidate.email}`).includes(term))&&(!area||areaOf(candidate)===area)&&(!stage||stageOf(candidate)===stage))}
function renderCandidates(){const list=filteredCandidates(),tbody=byId("lista-candidatos"),mobile=byId("mobile-candidates");tbody.replaceChildren();mobile.replaceChildren();byId("result-count").textContent=`${list.length} ${list.length===1?"profissional encontrado":"profissionais encontrados"}`;if(!list.length){renderEmpty(tbody,5,"Nenhum talento encontrado","Ajuste os filtros para ampliar a busca.");return}list.forEach(candidate=>{const row=document.createElement("tr"),personCell=document.createElement("td"),contact=document.createElement("td"),area=document.createElement("td"),stage=document.createElement("td"),actions=document.createElement("td");personCell.append(personBlock(candidate));contact.className="contact-cell";contact.append(textElement("span","",candidate.email),textElement("small","",candidate.telefone||"Telefone não informado"));area.append(textElement("span","area-badge",areaOf(candidate)));stage.append(textElement("span",`stage-badge stage-${stageOf(candidate)}`,stageLabel(stageOf(candidate))));actions.className="action-cell";const detail=textElement("button","action-link","Ver perfil");detail.type="button";detail.addEventListener("click",()=>openCandidate(candidate));actions.append(detail);if(phoneDigits(candidate.telefone))actions.append(actionLink("WhatsApp",whatsappUrl(candidate),"whatsapp"));row.append(personCell,contact,area,stage,actions);tbody.append(row);const card=textElement("article","mobile-card"),top=textElement("div","mobile-card-top");top.append(personBlock(candidate),textElement("span",`stage-badge stage-${stageOf(candidate)}`,stageLabel(stageOf(candidate))));card.append(top,textElement("span","area-badge",areaOf(candidate)));const detailMobile=textElement("button","action-link","Ver perfil");detailMobile.addEventListener("click",()=>openCandidate(candidate));const mobileActions=textElement("div","mobile-actions");mobileActions.append(detailMobile);if(phoneDigits(candidate.telefone))mobileActions.append(actionLink("WhatsApp",whatsappUrl(candidate),"whatsapp"));card.append(mobileActions);mobile.append(card)})}
function stageLabel(stage){return({novo:"Novo",triagem:"Triagem",entrevista:"Entrevista",finalista:"Finalista",contratado:"Contratado"})[stage]||"Novo"}
byId("search-input").addEventListener("input",renderCandidates);byId("area-filter").addEventListener("change",renderCandidates);byId("stage-filter").addEventListener("change",renderCandidates);byId("refresh-button").addEventListener("click",loadWorkspace);

function filteredLeads(){const term=normalize(byId("lead-search").value),status=byId("lead-status-filter").value;return leads.filter(lead=>(!term||normalize(`${lead.empresa} ${lead.nome_contato} ${lead.email_corporativo}`).includes(term))&&(!status||(lead.status||"novo")===status))}
function renderLeads(){const list=filteredLeads(),tbody=byId("lista-leads"),mobile=byId("mobile-leads");tbody.replaceChildren();mobile.replaceChildren();byId("leads-result-count").textContent=`${list.length} ${list.length===1?"empresa encontrada":"empresas encontradas"}`;if(!list.length){renderEmpty(tbody,5,"Nenhum contato encontrado","Novas solicitações comerciais aparecerão aqui.");return}list.forEach(lead=>{const row=document.createElement("tr"),company=document.createElement("td"),contact=document.createElement("td"),interest=document.createElement("td"),statusCell=document.createElement("td"),actions=document.createElement("td");company.append(textElement("strong","",lead.empresa||"Empresa não informada"));contact.className="contact-cell";contact.append(textElement("span","",lead.nome_contato),textElement("small","",lead.email_corporativo));interest.append(textElement("span","area-badge",lead.servico_interesse||"Consultoria"));statusCell.append(createLeadStatus(lead));actions.className="action-cell";if(lead.email_corporativo)actions.append(actionLink("E-mail",`mailto:${lead.email_corporativo}`));if(phoneDigits(lead.telefone_empresa))actions.append(actionLink("WhatsApp",whatsappUrl(lead),"whatsapp"));row.append(company,contact,interest,statusCell,actions);tbody.append(row);const card=textElement("article","mobile-card");card.append(textElement("strong","",lead.empresa),textElement("small","",lead.nome_contato),textElement("span","area-badge",lead.servico_interesse||"Consultoria"),createLeadStatus(lead));mobile.append(card)})}
function createLeadStatus(lead){const select=document.createElement("select");select.className="inline-status";[["novo","Novo"],["contatado","Contatado"],["proposta","Proposta"],["convertido","Convertido"]].forEach(([value,label])=>{const option=textElement("option","",label);option.value=value;select.append(option)});select.value=lead.status||"novo";select.addEventListener("change",async()=>{const{error}=await supabaseClient.from("leads_empresas").update({status:select.value}).eq("id",lead.id);if(error){select.value=lead.status||"novo";alert("Para salvar o status, aplique a configuração complementar do Supabase.")}else lead.status=select.value});return select}
byId("lead-search").addEventListener("input",renderLeads);byId("lead-status-filter").addEventListener("change",renderLeads);

function renderJobsAdmin(unavailable=false){const root=byId("admin-jobs-list");root.replaceChildren();byId("jobs-result-count").textContent=unavailable?"Módulo aguardando configuração":`${jobs.length} vagas cadastradas`;if(unavailable){root.append(createNotice("Configuração necessária","Aplique o arquivo ATIVAR_MODULO_VAGAS.sql no Supabase para liberar publicação e candidaturas."));return}if(!jobs.length){root.append(createNotice("Nenhuma vaga cadastrada","Use o formulário ao lado para publicar a primeira oportunidade."));return}jobs.forEach(job=>{const card=textElement("article","admin-job-card"),content=document.createElement("div");content.append(textElement("span","panel-kicker",`${job.area||"Área"} · ${job.modalidade||"A combinar"}`),textElement("h3","",job.titulo),textElement("p","",job.cidade||"Local a definir"));const toggle=textElement("button",job.ativa===false?"job-toggle":"job-toggle active",job.ativa===false?"Inativa":"Ativa");toggle.type="button";toggle.addEventListener("click",async()=>{const next=job.ativa===false;const{error}=await supabaseClient.from("vagas").update({ativa:next}).eq("id",job.id);if(!error){job.ativa=next;renderJobsAdmin(false);updateMetrics()}});card.append(content,toggle);root.append(card)})}
function createNotice(title,message){const notice=textElement("div","admin-notice");notice.append(textElement("strong","",title),textElement("p","",message));return notice}
byId("job-form").addEventListener("submit",async event=>{event.preventDefault();const button=byId("job-submit"),status=byId("job-form-status");button.disabled=true;status.textContent="Publicando oportunidade...";status.classList.remove("error");const payload={titulo:byId("job-title").value.trim(),area:byId("job-area").value.trim(),cidade:byId("job-city").value.trim(),modalidade:byId("job-mode-input").value,tipo:byId("job-type").value,resumo:byId("job-summary").value.trim(),descricao:byId("job-description").value.trim(),responsabilidades:byId("job-responsibilities").value.trim(),requisitos:byId("job-requirements").value.trim(),salario:byId("job-salary").value.trim(),validade:byId("job-valid-through").value||null,ativa:true};const{error}=await supabaseClient.from("vagas").insert([payload]);if(error){console.error("Falha ao publicar vaga:",error);const message=String(error.message||"");status.textContent=/row-level security|permission denied|42501/i.test(message)?"Sua conta está conectada, mas ainda não recebeu permissão para publicar vagas.":/schema cache|could not find|PGRST205/i.test(message)?"O módulo ainda está sincronizando. Aguarde alguns segundos e tente novamente.":`Não foi possível publicar: ${message||"verifique a configuração do Supabase."}`;status.classList.add("error")}else{event.target.reset();status.textContent="Vaga publicada com sucesso e enviada ao portal.";await loadJobs();updateMetrics()}button.disabled=false});

function openCandidate(candidate){activeCandidate=candidate;byId("drawer-id").value=candidate.id;byId("drawer-name").textContent=candidate.nome||"Candidato";byId("drawer-contact").textContent=`${candidate.email||""} · ${candidate.telefone||""}`;byId("drawer-stage").value=stageOf(candidate);byId("drawer-tags").value=candidate.tags||"";byId("drawer-notes").value=candidate.observacoes||"";byId("candidate-update-status").textContent="";const resume=byId("drawer-resume");resume.href=candidate.url_curriculo||"#";resume.hidden=!candidate.url_curriculo;const drawer=byId("candidate-drawer");drawer.hidden=false;requestAnimationFrame(()=>drawer.classList.add("open"));document.body.style.overflow="hidden"}
function closeDrawer(){const drawer=byId("candidate-drawer");drawer.classList.remove("open");document.body.style.overflow="";setTimeout(()=>drawer.hidden=true,220)}document.querySelectorAll("[data-drawer-close]").forEach(el=>el.addEventListener("click",closeDrawer));
byId("candidate-update-form").addEventListener("submit",async event=>{event.preventDefault();const status=byId("candidate-update-status"),payload={status_processo:byId("drawer-stage").value,tags:byId("drawer-tags").value.trim(),observacoes:byId("drawer-notes").value.trim()};status.textContent="Salvando...";status.classList.remove("error");const{error}=await supabaseClient.from("candidatos").update(payload).eq("id",byId("drawer-id").value);if(error){status.textContent="Aplique a configuração complementar do Supabase para salvar o acompanhamento.";status.classList.add("error");return}Object.assign(activeCandidate,payload);status.textContent="Acompanhamento atualizado.";renderCandidates();updateMetrics()});

function renderEmpty(tbody,colspan,title,message){const row=document.createElement("tr"),cell=document.createElement("td"),empty=textElement("div","empty-state");cell.colSpan=colspan;empty.append(textElement("strong","",title),textElement("span","",message));cell.append(empty);row.append(cell);tbody.append(row)}
function renderTableError(id,colspan,message){const tbody=byId(id);tbody.replaceChildren();renderEmpty(tbody,colspan,"Não foi possível carregar",message)}
supabaseClient.auth.onAuthStateChange((event,session)=>{if(session)showDashboard(session);else showLogin()});
supabaseClient.auth.getSession().then(({data})=>{if(data.session)showDashboard(data.session);else showLogin()});
