const SUPABASE_URL="https://qaviuelxsokbdpllqrap.supabase.co",SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhdml1ZWx4c29rYmRwbGxxcmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3Nzg4OTYsImV4cCI6MjEwMTM1NDg5Nn0.zvk7kGck96OM3kyTfLE-5Rr968ErvAYDXPKoA2f_e_s";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY),$=id=>document.getElementById(id);let job=null,activeModal=null;
function make(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
function renderSection(parent,title,text){if(!text)return;parent.append(make("h2","",title),make("p","",text))}
function employmentType(type){return({Efetivo:"FULL_TIME",Temporário:"TEMPORARY",Projeto:"CONTRACTOR",Estágio:"INTERN"})[type]||"OTHER"}
const UNIT_STATES={"sao jose dos campos":"SP","sao paulo":"SP","campinas":"SP","jundiai":"SP","pindamonhangaba":"SP","embu das artes":"SP","extrema":"MG"};
function plain(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function parseLocation(raw){const parts=String(raw||"").split(/\s*[\/,\-–]\s*/).map(part=>part.trim()).filter(Boolean),city=parts[0]||"",uf=parts.find((part,index)=>index>0&&/^[A-Za-z]{2}$/.test(part));return{city,region:uf?uf.toUpperCase():UNIT_STATES[plain(city)]}}
function addJobSchema(current){const config=window.MAIORH_CONFIG||{},organization=config.organization||{},site=(config.siteUrl||location.origin).replace(/\/$/,""),jobUrl=`${site}/vaga.html?id=${encodeURIComponent(current.id)}`,description=[current.resumo,current.descricao,current.responsabilidades,current.requisitos].filter(Boolean).join("\n\n"),schema={"@context":"https://schema.org","@type":"JobPosting",title:current.titulo,description,identifier:{"@type":"PropertyValue",name:organization.name||"RHMaior Consulting",value:String(current.id)},datePosted:(current.created_at||new Date().toISOString()).slice(0,10),directApply:true,url:jobUrl,employmentType:employmentType(current.tipo),hiringOrganization:{"@type":"Organization",name:organization.name||"RHMaior Consulting",sameAs:site,logo:`${site}/logo-rhmaior.jpg`}};if(current.validade)schema.validThrough=current.validade;if(current.modalidade==="Remoto"){schema.jobLocationType="TELECOMMUTE";schema.applicantLocationRequirements={"@type":"Country",name:"BR"}}else{const place=parseLocation(current.cidade),address={"@type":"PostalAddress",addressLocality:place.city||organization.city||"São José dos Campos",addressCountry:organization.country||"BR"};if(place.region)address.addressRegion=place.region;else if(!place.city)address.addressRegion=organization.state;schema.jobLocation={"@type":"Place",address}}const old=document.getElementById("job-schema");if(old)old.remove();const script=document.createElement("script");script.id="job-schema";script.type="application/ld+json";script.textContent=JSON.stringify(schema);document.head.append(script)}
async function loadJob(){const id=new URLSearchParams(location.search).get("id");if(!id){showError("Oportunidade não encontrada.");return}const{data,error}=await supabaseClient.from("vagas").select("*").eq("id",id).eq("ativa",true).single();if(error||!data){showError("Esta oportunidade não está mais disponível.");return}job=data;document.title=`${job.titulo} | RHMaior Consulting`;document.querySelector('meta[name="description"]').content=job.resumo||`Oportunidade para ${job.titulo}.`;$("canonical-link").href=`${((window.MAIORH_CONFIG||{}).siteUrl||location.origin).replace(/\/$/,"")}/vaga.html?id=${encodeURIComponent(job.id)}`;renderJob();addJobSchema(job);setupShareLinks(job)}
function setupShareLinks(current){const shareUrl=`${location.origin}${location.pathname}?id=${encodeURIComponent(current.id)}`,shareText=`${current.titulo} · RHMaior Consulting`;$("share-whatsapp").href=`https://wa.me/?text=${encodeURIComponent(shareText+" "+shareUrl)}`;$("share-linkedin").href=`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`}
function renderJob(){const hero=$("job-hero-content");hero.replaceChildren();const meta=make("div","job-meta detail-meta");meta.append(make("span","",job.area||"Oportunidade"),make("span","",job.modalidade||"A combinar"),make("span","",job.cidade||"Local a definir"),make("span","",job.tipo||"Contratação"));hero.append(meta,make("h1","",job.titulo),make("p","detail-summary",job.resumo||"Conheça os detalhes desta oportunidade."));const body=$("job-body");body.replaceChildren();renderSection(body,"Sobre a oportunidade",job.descricao||job.resumo);renderSection(body,"Responsabilidades",job.responsabilidades);renderSection(body,"Requisitos",job.requisitos);if(job.salario)renderSection(body,"Faixa salarial",job.salario);const notice=make("div","detail-notice");notice.append(make("strong","","Processo seguro e gratuito"),make("p","","A RHMaior não cobra valores de candidatos para participação em processos seletivos."));body.append(notice);$("job-sidebar").hidden=false;$("detail-apply").addEventListener("click",openApplication)}
function showError(message){const hero=$("job-hero-content");hero.replaceChildren(make("span","eyebrow eyebrow-dark","Oportunidade"),make("h1","",message));const body=$("job-body");body.replaceChildren();const notice=make("div","jobs-empty");notice.append(make("strong","","Consulte outras vagas"),make("a","button button-dark","Ver oportunidades →"));notice.querySelector("a").href="vagas.html";body.append(notice)}
function openApplication(){$("application-job-id").value=job.id;$("application-job").textContent=`${job.titulo} · ${job.cidade||job.modalidade||""}`;activeModal=$("application-modal");activeModal.hidden=false;requestAnimationFrame(()=>activeModal.classList.add("is-open"));document.body.classList.add("modal-open")}
function closeModal(){if(!activeModal)return;const modal=activeModal;modal.classList.remove("is-open");document.body.classList.remove("modal-open");activeModal=null;setTimeout(()=>modal.hidden=true,220)}document.querySelectorAll("[data-close]").forEach(el=>el.addEventListener("click",closeModal));document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
$("copy-job-link").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);$("copy-job-link").textContent="Link copiado"}catch{$("copy-job-link").textContent="Copie o endereço do navegador"}});
$("application-form").addEventListener("submit",async event=>{event.preventDefault();const button=$("application-submit"),status=$("application-status"),file=$("application-file").files[0];if(!file||!file.name.toLowerCase().endsWith(".pdf")||file.size>10*1024*1024){status.textContent="Envie um PDF válido de até 10 MB.";status.classList.add("is-error");return}button.disabled=true;status.classList.remove("is-error");status.textContent="Enviando candidatura...";try{const path=`${Date.now()}_${crypto.randomUUID()}.pdf`,email=$("application-email").value.trim().toLowerCase();const{error:uploadError}=await supabaseClient.storage.from("curriculos").upload(path,file,{contentType:"application/pdf",upsert:false});if(uploadError)throw uploadError;const{data:urlData}=supabaseClient.storage.from("curriculos").getPublicUrl(path),candidate={nome:$("application-name").value.trim(),email,telefone:$("application-phone").value.trim(),vaga_interesse:job.titulo,url_curriculo:urlData.publicUrl};const{error:candidateError}=await supabaseClient.from("candidatos").upsert([candidate],{onConflict:"email"});if(candidateError)throw candidateError;await supabaseClient.from("candidatos").update({consentimento_lgpd:true,data_consentimento:new Date().toISOString()}).eq("email",email);const{error:applicationError}=await supabaseClient.from("candidaturas_vagas").insert([{vaga_id:job.id,candidato_email:email}]);if(applicationError)throw applicationError;event.target.reset();status.textContent="Candidatura recebida com sucesso!";setTimeout(closeModal,1800)}catch(error){console.error("Falha na candidatura:",error);status.textContent="Não foi possível concluir. Tente novamente mais tarde.";status.classList.add("is-error")}finally{button.disabled=false}});
loadJob();
